set timing on;

DECLARE
  SEARCH_KEYWORD VARCHAR2(20);
  SEARCH_USER_ID NUMBER;
BEGIN
  SEARCH_KEYWORD := 'lithuanian';
  SEARCH_USER_ID := 1;

  TEST_SEARCH_DOC(
    SEARCH_KEYWORD => SEARCH_KEYWORD,
    SEARCH_USER_ID => SEARCH_USER_ID
  );
END;
